# Backend Server Deployment
# Exposes the dashboard and control API
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-server
  namespace: fraud-det-v3
  labels:
    app: "backend-server"
    tier: "management"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "backend-server"
  template:
    metadata:
      labels:
        app: "backend-server"
        tier: "management"
    spec:
      serviceAccountName: fraud-backend
      containers:
        - name: backend-server
          image: pduraiswamy16722/fraud-det-v3-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              name: http
          env:
            - name: PROMETHEUS_URL
              value: "http://10.23.181.153:9090"
            - name: CONFIG_MODE
              value: "dual"
            - name: CPU_VOLUME_PATH
              value: "/mnt/cpu-fb"
            - name: GPU_VOLUME_PATH
              value: "/mnt/gpu-fb"
            - name: PURE_SERVER
              value: "true"
            - name: PYTHONUNBUFFERED
              value: "1"
          volumeMounts:
            - name: cpu-fb
              mountPath: /mnt/cpu-fb
            - name: gpu-fb
              mountPath: /mnt/gpu-fb
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "1000m"
              memory: "2Gi"
      volumes:
        - name: cpu-fb
          persistentVolumeClaim:
            claimName: fraud-det-v3-cpu-fb-v6
        - name: gpu-fb
          persistentVolumeClaim:
            claimName: fraud-det-v3-gpu-fb-v6
---
# Service for Backend Dashboard
apiVersion: v1
kind: Service
metadata:
  name: backend-server
  namespace: fraud-det-v3
  labels:
    app: "backend-server"
spec:
  type: NodePort
  selector:
    app: "backend-server"
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 30880
