# CPU Machine + Local SSD Configuration
# Applies to a single node with local storage at /mnt/data/fraud-pipeline
# Run: kubectl apply -f k8s_configs/cpu-local-ssd.yaml

apiVersion: v1
kind: Namespace
metadata:
  name: fraud-pipeline
  labels:
    app.kubernetes.io/name: fraud-pipeline
---
# Local PV using hostPath (simulating local SSD)
apiVersion: v1
kind: PersistentVolume
metadata:
  name: fraud-pipeline-local-pv
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/fraud-pipeline"
    type: DirectoryOrCreate
---
# PVC binding to the local PV
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fraud-pipeline-flashblade  # Keep name to match deployment volumes
  namespace: fraud-pipeline
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
# Pod 1: CPU Generation (data-gather)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-gather
  namespace: fraud-pipeline
  labels:
    app: "data-gather"
    tier: "generation"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "data-gather"
  template:
    metadata:
      labels:
        app: "data-gather"
        tier: "generation"
    spec:
      containers:
        - name: data-gather
          image: fraud-pipeline/data-gather:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: CONTINUOUS_MODE
              value: "true"
            - name: QUEUE_TYPE
              value: "flashblade"  # App logic still uses file queue
            - name: FLASHBLADE_PATH
              value: "/mnt/flashblade"
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: GENERATION_RATE
              value: "50000"
            - name: NUM_WORKERS
              value: "8"
            - name: CHUNK_SIZE
              value: "50000"
          volumeMounts:
            - name: flashblade
              mountPath: /mnt/flashblade
          resources:
            requests:
              cpu: "2000m"
              memory: "4Gi"
            limits:
              cpu: "8000m"
              memory: "16Gi"
      volumes:
        - name: flashblade
          persistentVolumeClaim:
            claimName: fraud-pipeline-flashblade
---
# Pod 2: CPU Preprocessing (Polars)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: preprocessing-cpu
  namespace: fraud-pipeline
  labels:
    app: "preprocessing-cpu"
    tier: "preprocessing"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "preprocessing-cpu"
  template:
    metadata:
      labels:
        app: "preprocessing-cpu"
        tier: "preprocessing"
    spec:
      containers:
        - name: preprocessing-cpu
          image: fraud-pipeline/preprocessing-cpu:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: CONTINUOUS_MODE
              value: "true"
            - name: QUEUE_TYPE
              value: "flashblade"
            - name: FLASHBLADE_PATH
              value: "/mnt/flashblade"
            - name: PYTHONUNBUFFERED
              value: "1"
          volumeMounts:
            - name: flashblade
              mountPath: /mnt/flashblade
          resources:
            requests:
              cpu: "2000m"
              memory: "8Gi"
            limits:
              cpu: "8000m"
              memory: "32Gi"
      volumes:
        - name: flashblade
          persistentVolumeClaim:
            claimName: fraud-pipeline-flashblade
---
# Pod 5: CPU Inference (XGBoost fallback)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inference-cpu
  namespace: fraud-pipeline
  labels:
    app: "inference-cpu"
    tier: "inference"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "inference-cpu"
  template:
    metadata:
      labels:
        app: "inference-cpu"
        tier: "inference"
    spec:
      containers:
        - name: inference-cpu
          image: fraud-pipeline/inference-cpu:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: CONTINUOUS_MODE
              value: "true"
            - name: QUEUE_TYPE
              value: "flashblade"
            - name: FLASHBLADE_PATH
              value: "/mnt/flashblade"
            # No TRITON_URL needed for CPU fallback/standalone
            - name: PYTHONUNBUFFERED
              value: "1"
          volumeMounts:
            - name: flashblade
              mountPath: /mnt/flashblade
          resources:
            requests:
              cpu: "1000m"
              memory: "4Gi"
            limits:
              cpu: "4000m"
              memory: "16Gi"
      volumes:
        - name: flashblade
          persistentVolumeClaim:
            claimName: fraud-pipeline-flashblade
---
# ServiceAccount + RBAC for backend
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fraud-backend
  namespace: fraud-pipeline
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fraud-backend-role
  namespace: fraud-pipeline
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "patch", "update"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fraud-backend-binding
  namespace: fraud-pipeline
subjects:
  - kind: ServiceAccount
    name: fraud-backend
    namespace: fraud-pipeline
roleRef:
  kind: Role
  name: fraud-backend-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fraud-backend-nodes
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fraud-backend-nodes-binding
subjects:
  - kind: ServiceAccount
    name: fraud-backend
    namespace: fraud-pipeline
roleRef:
  kind: ClusterRole
  name: fraud-backend-nodes
  apiGroup: rbac.authorization.k8s.io
---
# Backend: Dashboard API
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: fraud-pipeline
  labels:
    app: "backend"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "backend"
  template:
    metadata:
      labels:
        app: "backend"
    spec:
      serviceAccountName: fraud-backend
      containers:
        - name: backend
          image: fraud-pipeline/backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              name: http
          env:
            - name: QUEUE_TYPE
              value: "flashblade"
            - name: FLASHBLADE_PATH
              value: "/mnt/flashblade"
            - name: PROMETHEUS_URL
              value: ""
            - name: PURE_SERVER
              value: "false"
          volumeMounts:
            - name: flashblade
              mountPath: /mnt/flashblade
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
      volumes:
        - name: flashblade
          persistentVolumeClaim:
            claimName: fraud-pipeline-flashblade
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: fraud-pipeline
  labels:
    app: "backend"
spec:
  selector:
    app: "backend"
  ports:
    - name: http
      port: 8000
      targetPort: 8000
